#!/bin/bash

# MongoDB Migration - Batch Service Update Script
# This script helps identify what needs to be updated

echo "======================================"
echo "MongoDB Migration - Service Analysis"
echo "======================================"
echo ""

echo "Searching for Prisma imports in services..."
grep -r "PrismaService" src/modules --include="*.service.ts" | wc -l
echo ""

echo "Services still using PrismaService:"
grep -r "PrismaService" src/modules --include="*.service.ts"
echo ""

echo "======================================"
echo "Migration Checklist:"
echo "======================================"
echo ""
echo "✅ 1. Users Service - MIGRATED"
echo "⏳ 2. Auth Service - NEEDS MIGRATION"
echo "⏳ 3. Products Service - NEEDS MIGRATION"
echo "⏳ 4. Categories Service - NEEDS MIGRATION"
echo "⏳ 5. Brands Service - NEEDS MIGRATION"
echo "⏳ 6. Cart Service - NEEDS MIGRATION"
echo "⏳ 7. Wishlist Service - NEEDS MIGRATION"
echo "⏳ 8. Orders Service - NEEDS MIGRATION"
echo "⏳ 9. Payments Service - NEEDS MIGRATION"
echo "⏳ 10. Reviews Service - NEEDS MIGRATION"
echo "⏳ 11. Banners Service - NEEDS MIGRATION"
echo "⏳ 12. Blogs Service - NEEDS MIGRATION"
echo "⏳ 13. Verification/OTP Service - NEEDS MIGRATION"
echo "⏳ 14. Admin Service - NEEDS MIGRATION"
echo "⏳ 15. Upload Service - CHECK IF NEEDS MIGRATION"
echo ""

echo "======================================"
echo "Quick Migration Steps for Each Service:"
echo "======================================"
echo ""
echo "1. Update imports in service file:"
echo "   - Remove: import { PrismaService } from '../../database/prisma.service';"
echo "   - Add: import { InjectModel } from '@nestjs/mongoose';"
echo "   - Add: import { Model, Types } from 'mongoose';"
echo "   - Add: import { ModelName } from '../../database/schemas';"
echo ""
echo "2. Update constructor:"
echo "   - Remove: constructor(private prisma: PrismaService) {}"
echo "   - Add: constructor(@InjectModel('ModelName') private modelNameModel: Model<ModelName>) {}"
echo ""
echo "3. Update module file:"
echo "   - Add: import { MongooseModule } from '@nestjs/mongoose';"
echo "   - Add: import { SchemaName, SchemaNameSchema } from '../../database/schemas';"
echo "   - Add to imports array: MongooseModule.forFeature([{ name: 'SchemaName', schema: SchemaNameSchema }])"
echo ""
echo "4. Update query methods:"
echo "   - findUnique/findFirst → findById or findOne"
echo "   - findMany → find"
echo "   - create → create"
echo "   - update → findByIdAndUpdate"
echo "   - delete → findByIdAndDelete"
echo "   - count → countDocuments"
echo ""

echo "======================================"
echo "Test after each migration:"
echo "======================================"
echo "npm run build"
echo ""
